Repository Swapnil-Pathare/Devops-Assignment-1, pull requests merged in 2022-04, with the labels that each got.

#1 Adding registration page
  registration.html
Labels: enhancement

#3 new home page added
  home.html
Labels: feature

#2 added a new demo html file
  demo.html
Labels: enhancement

#4 Added Login.html file
  login.html
Labels: feature

#5 added new filee
  test-file.tsx
Labels: enhancement, feature

#7 Feature 0.4
  about.html
  home.html
Labels: feature

#8 Adding my-website file
  my-website.html
Labels: enhancement, feature

#9 added new webpage
  my-website.html
Labels: enhancement, feature
